---
platform: linux
image_resource:
  type: registry-image
  source: {repository: golang, tag: 1.13.4}

inputs:
  - name: terraform-provider-alicloud
  - name: aliyun-cli

run:
  path: terraform-provider-alicloud/ci/tasks/build-package.sh
params:
  terraform_provider_bucket_name:   ""
  terraform_provider_bucket_region: ""
  terraform_provider_access_key:      ""
  terraform_provider_secret_key:      ""
