---
platform: linux

image_resource:
  type: registry-image
  source: {repository: golang, tag: 1.20.11}

inputs:
  - name: terraform-provider-alicloud
#  - name: aliyun-cli

outputs:
  - name: next-provider

run:
  path: terraform-provider-alicloud/ci/tasks/build-provider-next.sh
