---
platform: linux

image_resource:
  type: registry-image
  source: {repository: golang, tag: 1.13.4}

inputs:
  - name: terraform-provider-alicloud
  - name: aliyun-cli

run:
  path: terraform-provider-alicloud/ci/tasks/ci-test.sh
params:
  ALICLOUD_ACCESS_KEY:   ""
  ALICLOUD_SECRET_KEY:   ""
  ALICLOUD_REGION:       ""
  ALICLOUD_ACCOUNT_ID:   ""
  DING_TALK_TOKEN:       ""
  BUCKET_NAME:           "terraform-provider-ci"
  BUCKET_REGION:         "cn-beijing"
  ALICLOUD_RESOURCE_GROUP_ID : ""
  ALICLOUD_WAF_INSTANCE_ID: ""
  CONCOURSE_TARGET: ""
  CONCOURSE_TARGET_URL: ""
  CONCOURSE_TARGET_USER: ""
  CONCOURSE_TARGET_PASSWORD: ""
  TRIGGER_TARGET_PIPELINE: ""