---
platform: linux

image_resource:
  type: registry-image
  source: { repository: golang, tag: 1.13.4 }

inputs:
  - name: terraform-provider-alicloud
  - name: aliyun-cli
outputs:
  - name: terraform-provider-alicloud


run:
  path: terraform-provider-alicloud/ci/tasks/module-test.sh

params:
  ALICLOUD_ACCESS_KEY: ""
  ALICLOUD_SECRET_KEY: ""
  ALICLOUD_REGION: ""
  terraform_version: ""
  BUCKET_REGION: "cn-beijing"
  Stage: ""
