---
platform: linux

image_resource:
  type: registry-image
  source: {repository: golang, tag: 1.20.11}

inputs:
  - name: terraform-provider-alicloud
  - name: goreleaser
outputs:
  - name: terraform-provider-alicloud
run:
  path: terraform-provider-alicloud/ci/tasks/publish.sh
params:
  GITHUB_TOKEN: ""
  GPG_FINGERPRINT: ""

