name: Documentation Checks
on:
  push:
    branches:
      - master
  pull_request:
    pull_request_target:
      types:
        - opened
      paths:
        - .github/workflows/document-check.yml
        - .go-version
        - website/docs/**

jobs:
  markdown-link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          folder-path: "website/docs"
          file-extension: '.md'

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: avto-dev/markdown-lint@v1

  misspell:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: misspell
        uses: reviewdog/action-misspell@v1.11.1
        with:
          github_token: ${{secrets.github_token}}
          fail_on_error: true
          filter_mode: file
          locale: "US"
          path: ./website/docs

  terrafmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: terrafmt
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go install github.com/katbyte/terrafmt@latest
          terrafmt diff ./website --check --pattern '*.markdown'

  basic-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '3'
      - uses: actions/setup-go@v2
        with:
          go-version-file: .go-version
      - run: bash scripts/basic-check.sh

  Content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
      - uses: jitterbit/get-changed-files@v1
        id: files
        with:
          format: 'json'
      - name: Checking the docs content
        run: |
          readarray -t changed_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.added_modified }}')"
          for changed_file in ${changed_files[@]}; do
            if [[ ${changed_file} == "website/docs/"* ]]; then
                go run scripts/document/document_check.go ${changed_file}
            fi
          done

  Consistency:
    needs: Content
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Integration Test Check
        run: |
          git diff HEAD^ HEAD > diff.out
          go run scripts/consistency/consistency_check.go -fileNames="diff.out"

#  terraform-validate:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: import
#        run: |
#          echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
#      - uses: actions/setup-go@v2
#        with:
#          go-version: ${{ env.GO_VERSION }}
#      - name: terraform-validate
#        run: |
#          export PATH=$PATH:$(go env GOPATH)/bin
#          go get -t github.com/katbyte/terrafmt
#          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
#          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
#          echo ${FILES}
#          ./scripts/terraform-validate.sh "${FILES[@]}"
#          if [[ "$?" == "1" ]]; then
#            echo "Please Check the Terraform Grammer" && exit 1
#          fi


